version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
        - .:/code
    depends_on:
        - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/code
    env_file:
      - .env